@extends('includes.master')

@section('content')

    @if(!request()->get('webView'))
        @include('includes.header')
    @endif


    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <section class="pageContent" style="{{ request()->get('webView') ? 'margin-top: 3rem': '' }}">
                    <h1 class="text-center fw-bold">Privacy Policy</h1>
                    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure
                        of Your information when You use the Service and tells You about Your privacy rights and how the
                        law protects You. We use Your Personal data to provide and improve the Service. By using the
                        Service, You agree to the collection and use of information in accordance with this Privacy
                        Policy.</p>
                    <h2>Interpretation and Definitions</h2>

                    <h3>Interpretation</h3>
                    <p>The words of which the initial letter is capitalized have meanings defined under the following
                        conditions. The following definitions shall have the same meaning regardless of whether they
                        appear in singular or in plural.</p>

                    <h3>Definitions</h3>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul>
                        <li><strong>Account</strong> means a unique account created for You to access our Service or
                            parts of our Service.
                        </li>
                        <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under
                            common control with a party, where “control” means ownership of 50% or more of the shares,
                            equity interest or other securities entitled to vote for election of directors or other
                            managing authority.
                        </li>
                        <li><strong>Application</strong> means the software program provided by the Company downloaded
                            by You on any electronic device, named Cookie Streaming.
                        </li>
                        <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this
                            Agreement) refers to Cookie Streaming.
                        </li>
                        <li><strong>Country</strong> refers to Rajasthan, India.</li>
                        <li><strong>Device</strong> means any device that can access the Service such as a computer, a
                            cellphone or a digital tablet.
                        </li>
                        <li><strong>Personal Data</strong> is any information that relates to an identified or
                            identifiable individual.
                        </li>
                        <li><strong>Service</strong> refers to the Application.</li>
                        <li><strong>Service Provider</strong> means any natural or legal person who processes the data
                            on behalf of the Company. It refers to third-party companies or individuals employed by the
                            Company to facilitate the Service, to provide the Service on behalf of the Company, to
                            perform services related to the Service or to assist the Company in analyzing how the
                            Service is used.
                        </li>
                        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the
                            use of the Service or from the Service infrastructure itself (for example, the duration
                            of a page visit).
                        </li>
                    </ul>
                    <h2>Collecting and Using Your Personal Data</h2>
                    <p>When You use Our Service, We may collect certain Personal Data from You. This may include your
                        name, email address, phone number, and other contact information. We use this information to
                        provide and improve the Service, to communicate with You, and to comply with legal
                        obligations.</p>

                    <h2>Use of Your Personal Data</h2>
                    <p>The Company may use Personal Data for the following purposes:</p>
                    <ul>
                        <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                        <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal
                            Data You provide can give You access to different functionalities of the Service that are
                            available to You as a registered user.
                        </li>
                        <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of
                            electronic communication, such as a mobile application's push notifications regarding
                            updates or informative communications related to the functionalities, products or contracted
                            services, including the security updates, when necessary or reasonable for their
                            implementation.
                        </li>
                        <li>To provide You with news, special offers and general information about other goods, services
                            and events which we offer that are similar to those that you have already purchased or
                            enquired about unless You have opted not to receive such information.
                        </li>
                        <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                    </ul>

                    <h2>Disclosure of Your Personal Data</h2>
                    <p>The Company may disclose Your Personal Data in the good faith belief that such action is
                        necessary to:</p>
                    <ul>
                        <li>Comply with a legal obligation</li>
                        <li>Protect and defend the rights or property of the Company</li>
                        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                        <li>Protect the personal safety of users of the Service or the public</li>
                        <li>Protect against legal liability</li>
                    </ul>

                    <h2>Security of Your Personal Data</h2>
                    <p>The security of Your Personal Data is important to Us, but remember that no method of
                        transmission over the Internet, or method of electronic storage is 100% secure. While We strive
                        to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its
                        absolute security.</p>

                    <h2>Links to Other Websites</h2>
                    <p>Our Service may contain links to other websites that are not operated by Us. If You click on a
                        third-party link, You will be directed to that third party's site. We strongly advise You to
                        review the Privacy Policy of every site You visit.</p>

                    <h2>Changes to this Privacy Policy</h2>
                    <p>We may update our Privacy Policy from time to time. We will notify You of any changes by posting
                        the new Privacy Policy on this page.</p>
                    <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change
                        becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
                    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this
                        Privacy Policy are effective when they are posted on this page.</p>

                    <h2>Contact Us</h2>
                    <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                    <ul>
                        <li>By email: cookiestreamingservices@gmail.com</li>
                    </ul>

                </section>

            </div>
        </div>
    </div>



    @if(!request()->get('webView'))
        @include('includes.footer')
    @endif

@endsection



